# Generated by Django 3.2.7 on 2021-11-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contactNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
