# Generated by Django 3.2.9 on 2021-11-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211108_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='contactNumber',
            new_name='contact_number',
        ),
    ]
