# Generated by Django 3.2.9 on 2021-11-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_contactnumber_users_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='otp',
            field=models.IntegerField(default=0),
        ),
    ]
