# Generated by Django 3.2.9 on 2021-11-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211110_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='contact_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
